### ISSUE TITLE
Mode selection from pull-down menu

### ISSUE THREAD

**Issue by hitsub** [hitsub/CookieAssistant#68]
モード切替が煩雑なのでプルダウンからやりたい
以下の感じでいけそう
```html
<select id="pulldownTest" onChange="console.log(document.getElementById('pulldownTest').value);">
	<option value=0>あ</option>
	<option value=1>い</option>
	<option value=2>う</option>
</select>
```

見た目が完全に浮くのでCSSでどうにかできるか要検証

**Comment by hitsub** [comment]
これでだいたい一緒
![image](https://user-images.githubusercontent.com/5540614/135839375-c7429faa-6b87-4b37-89d5-902d6b151be6.png)
![image](https://user-images.githubusercontent.com/5540614/135839415-2fe8c448-cec2-4eee-974e-af614d72c8b1.png)

```css
select
{
	border:1px solid #e2dd48;
	border-color:#ece2b6 #875526 #733726 #dfbc9a;
	background:#000 url(img/darkNoise.jpg);
	background-image:url(img/shadedBordersSoft.png),url(img/darkNoise.jpg);
	background-size:100% 100%,auto;
	background-color:#000;
	border-radius:2px;
	box-shadow:0px 0px 1px 2px rgba(0,0,0,0.5),0px 2px 4px rgba(0,0,0,0.25),0px 0px 2px 2px #000 inset,0px 1px 0px 1px rgba(255,255,255,0.5) inset;
	text-shadow:0px 1px 1px #000;
	color:#ccc;
	line-height:100%;
	padding:1px 3px;
}
```
